updated template to include Returns and Throws
webdriverio/wddoc pull request #3
Opened 2017-04-25 21:22 UTC by jankcat

Updated the doc template to include `@return` and `@throws` jsdoc attributes, if they are present.

Note: the library already in use here supports `@return` but not `@returns`. If you approve the PR, I don't mind going through the existing jsdocs on the webdriverio project and converting instances of `@returns` to `@return` for compatibility.

2017-04-25 21:23 UTC, jankcat commented
@christian-bromann

2017-04-25 21:43 UTC, christian-bromann requested changes
> Note: the library already in use here supports @return but not @returns

Is `@return` not supported by dox or why switch to `@returns`

I definitely like adding the return value to the documentation. This is requested by a lot of people and would be super valuable. It is going to be a lot of work to go over all commands and add missing return objects 😉 

Same for `@throws`: it will be a lot of work to add these information to the command jsdocs but it would be definitely super valuable.

Regarding the format, I would prefer lists since you usually only have one return value (or multiple depending on the input)

2017-04-25 21:43 UTC, christian-bromann commented on templates/template.md.ejs
> +<? command.returnTags.forEach(function(returnTag) { ?>| <?= returnTag.joinedTypes.replace('=','').replace(/[|\/]/g,'/') ?> | <?= returnTag.description ?> |
I would prefer simple lists here, like:

### Returns
- __\<String\>__ some description about the property
- __\<Object\>__ an object that could look like:
    ```js
    {
        prop: "somevalue",
        prop2: true
    }
    ```

### Throws
- __RuntimeError__ the condition when it throws

2017-04-25 21:46 UTC, jankcat commented
It is "@return" that is supported, not "@returns". I have already forked and commited the main repo with all the "@returns" updated to the correct "@return", including the contribution doc, but have not PR'd it yet.

Sure, let me look at markdown format for lists. Something like:

- **RETURN_TYPE**: description

And:

- **EXCEPTION_TYPE**: description

Is that what you had in mind?

2017-04-25 21:50 UTC, jankcat commented
Oh gotcha. I see the example inline

2017-04-25 22:04 UTC, jankcat commented
Okay. I have updated it as such:

## Example 1, String Returned
Input: 
<pre>
 * @return {String}      The text of the currently displayed alert.
 * @throws {RuntimeError}   If no alert is present. The seleniumStack.type parameter will equal 'NoAlertOpenError'.
</pre>

Output:
<pre>
### Returns

- **&lt;String&gt;**: The text of the currently displayed alert.

### Throws

- **RuntimeError**: If no alert is present. The seleniumStack.type parameter will equal 'NoAlertOpenError'.
</pre>

## Example 2, Object Returned
Input:
<pre>
 * @return {Object}      Some object with params:
 
 ```
 {
    param:value
 }
 ```
 * @throws {RuntimeError}   If no alert is present. The seleniumStack.type parameter will equal 'NoAlertOpenError'.
</pre>

Output:
<pre>
### Returns

- **&lt;Object&gt;**: Some object with params:
 ```
 {
    param:value
 }
 ```

### Throws

- **RuntimeError**: If no alert is present. The seleniumStack.type parameter will equal 'NoAlertOpenError'.
</pre>

2017-04-25 22:05 UTC, jankcat commented
Note that the generator doesn't understand to put the returned object example on a newLine unless there is a newLine gap between the description and the <pre>```</pre>, as seen in example 2.

2017-04-26 08:04 UTC, christian-bromann commented
@jankcat thanks for the update. Just wondering if `**<Object>**` should be `**\<Object\>**` otherwise markdown interprets it as tag, e.g.

**<Object>**

vs

**\<Object\>**

2017-04-26 08:06 UTC, christian-bromann approved these changes
Oh perfect you are using `&lt;` and `&gt;` 👍 

This is gonna be super helpful for our docs. Thanks so much!

2017-04-26 08:06 UTC, merged

2017-04-26 15:06 UTC, jankcat commented
No problem! I have some downtime so I thought I would look for things to do hah.